language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/Alarm/Alarm.ino
    - PLATFORMIO_CI_SRC=examples/FixedCycleTimer/FixedCycleTimer.ino
    - PLATFORMIO_CI_SRC=examples/FrequencyOutput/FrequencyOutput.ino
    - PLATFORMIO_CI_SRC=examples/InitAndRead/InitAndRead.ino
    - PLATFORMIO_CI_SRC=examples/TimeUpdateInterrupt/TimeUpdateInterrupt.ino

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="." --board=uno